language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:kalakris/cmake -y
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake
  - sudo apt-get install -y libqt4-dev libdcmtk2-dev libinsighttoolkit3-dev libgdcm2-dev
  - sudo apt-get install -y xpra xserver-xorg-video-dummy

before_script:
  - "ls"
  - "xpra --xvfb=\"Xorg +extension GLX -config `pwd`/Applications/Testing/dummy.xorg.conf -logfile ${HOME}/.xpra/xorg.log\"  start :9"
  - mkdir build
  - cd build
  - "cmake -DCTK_ENABLE_DICOM:BOOL=ON .."

script: "make && (cd CTK-build; env DISPLAY=:9 make Experimental)"

after_script:
  - "xpra stop :9"
  - "cat ~/.xpra/*"
