language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libqt4-dev libdcmtk2-dev libinsighttoolkit3-dev libgdcm2-dev

before_script:
  - echo before_script in `pwd`
  - mkdir build
  - cd build
  - ../cmake-2.8.12.2-Linux-i386/bin/cmake ..

script: make
